# Setup
title:            Order of the Mimosa
tagline:          'a project'
description:      'This is a project that we are working on for project reasons.'
url:              https://scottbot.github.io/privacy-workshop-scratch
baseurl:          ''
paginate:         5

# About and contact
author:
  name:           'all of us'
  url:            #

# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist

# Custom vars
version:          3.0.0
